name: Super-Linter

on:
  pull_request:
    branches: [master, main]


jobs: 
  build: 
    name: Codebase Refactorer and Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
      
      - name: Lint Codebase
      uses: github/super-linter@v4.9.7
      env:
        VALIDATE_ALL_CODEBASE: true
        VALIDATE_JAVASCRIPT_ES: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
